import type { Job, Technician } from './types';

export const jobs: Job[] = [
  {
    id: 'job-123',
    deviceType: 'Television',
    deviceIcon: 'Tv2',
    problemSummary: 'Screen is flickering and has vertical lines.',
    location: 'Downtown',
    estimatedPrice: '1500-2500',
    inspectionCharge: 300,
    status: 'new',
    customer: {
      name: 'John Doe',
      phone: '9876543210',
      address: '123 Main St, Downtown, Anytown 12345',
    },
    problemDetails: 'The Samsung 55" QLED TV screen started flickering yesterday. It now shows persistent vertical lines across the entire display. Sound is working fine. Issue is present on all inputs.',
    photos: ['job-photo-3'],
  },
  {
    id: 'job-456',
    deviceType: 'Washing Machine',
    deviceIcon: 'WashingMachine',
    problemSummary: 'Not draining water and making a loud noise.',
    location: 'Suburbia',
    estimatedPrice: '800-1200',
    inspectionCharge: 250,
    status: 'active',
    activeStatus: 'reached_location',
    customer: {
      name: 'Jane Smith',
      phone: '8765432109',
      address: '456 Oak Ave, Suburbia, Anytown 54321',
    },
    problemDetails: 'My LG front-load washing machine completed a cycle but did not drain the water. When I tried to run a drain/spin cycle, it made a very loud grinding noise and still did not drain. The door is locked with water inside.',
    photos: ['job-photo-2'],
  },
  {
    id: 'job-789',
    deviceType: 'Smartphone',
    deviceIcon: 'Smartphone',
    problemSummary: 'Cracked screen, touch not responsive.',
    location: 'City Center',
    estimatedPrice: '4000-6000',
    inspectionCharge: 150,
    status: 'active',
    activeStatus: 'scheduled',
    customer: {
      name: 'Alex Johnson',
      phone: '7654321098',
      address: '789 Pine Ln, City Center, Anytown 67890',
    },
    problemDetails: 'Dropped my iPhone 13. The screen is heavily cracked, especially on the top right corner. The display shows images, but the touch is not working at all. I cannot unlock the phone.',
    photos: ['job-photo-1'],
  },
  {
    id: 'job-101',
    deviceType: 'Refrigerator',
    deviceIcon: 'Refrigerator',
    problemSummary: 'Not cooling, freezer is fine.',
    location: 'Northside',
    estimatedPrice: '1200-2000',
    inspectionCharge: 300,
    status: 'completed',
    activeStatus: 'repair_completed',
    customer: {
      name: 'Emily Davis',
      phone: '6543210987',
      address: '101 Maple Dr, Northside, Anytown 13579',
    },
    problemDetails: 'The freezer section is working perfectly, but the main refrigerator compartment is not cooling. I can hear the compressor running. Cleaned the coils but it did not help.',
    photos: [],
    finalCost: 1800,
    spareParts: 'Damper Control Assembly',
    notes: 'Replaced faulty damper control. Tested for 30 mins, temperature is dropping correctly now.'
  },
    {
    id: 'job-112',
    deviceType: 'Air Conditioner',
    deviceIcon: 'AirVent',
    problemSummary: 'AC not turning on.',
    location: 'West End',
    estimatedPrice: '1000-1500',
    inspectionCharge: 350,
    status: 'new',
    customer: {
      name: 'Michael Brown',
      phone: '5432109876',
      address: '212 Birch Rd, West End, Anytown 24680',
    },
    problemDetails: 'The split AC unit is completely dead. Not responding to the remote or the manual power button. Checked the circuit breaker and it is fine. The remote has new batteries.',
    photos: [],
  },
];

export const technicianProfile: Technician = {
  name: 'Ravi Kumar',
  phone: '9988776655',
  serviceCategories: ['TV', 'Washing Machine', 'Refrigerator', 'AC', 'Mobile'],
  areaCovered: 'Anytown',
  totalJobs: 134,
  avatarUrl: 'https://picsum.photos/seed/tech/200/200',
  lifetimeEarnings: 254200,
  todaysEarnings: 1800,
};

export const sparePartsInventory = [
    "Belt",
    "Capacitor",
    "Screen",
    "Compressor",
    "Thermostat",
    "Drain pump",
    "Heating element",
    "Motherboard",
    "Fan motor",
    "Damper Control Assembly"
].join(', ');
